### ISSUE TITLE
Clojure link appears twice

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/micro-manager.github.io#146]
Id fix it but its not clear to me why this happens...

<img width="211" alt="Screen Shot 2024-06-25 at 10 02 49 AM" src="https://github.com/micro-manager/micro-manager.github.io/assets/7969470/b8c34f38-1675-4830-95e8-446419838d19">

**Comment by marktsuchida** [comment]
Maybe because it appears twice in _includes/layout/menu? I think it would be okay to delete both, to be honest.

**Comment by henrypinkard** [comment]
Agreed

https://github.com/micro-manager/micro-manager.github.io/pull/147
