### ISSUE TITLE
We need to rename the repo to micro-manager.github.io

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager.github.io#32]
When we point our domain (micro-manager.org) to GitHub pages, we cannot point it to `https://micro-manager.github.io/micro-manager.org/*`; the [custom domain replaces micro-manager.github.io](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/about-custom-domains-and-github-pages#supported-custom-domains), so with the current repo name we would end up with `https://micro-manager.org/micro-manager.org/*`, which we certainly don't want.

To serve from the root path under the domain name, the repo [needs to be named micro-manager.github.io](https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites).

Incidentally, renaming the repo will also fix the problem where the content currently served at https://micro-manager.github.io/micro-manager.org/ doesn't render correctly (because that problem is caused by relative URLs with an absolute path like `/media/foo` pointing outside of the `micro-manager.org` directory).

**Comment by marktsuchida** [comment]
Well, actually not true (thanks to @ctrueden for enlightening me). See https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain and also a real example at https://github.com/ctrueden/restlessgamer.net/blob/gh-pages/CNAME.

But it might still be easier to rename, which allows testing with the github.io domain (or else we can point a custom domain to test).

**Comment by ctrueden** [comment]
Yeah, it's true that if you rename it, you can just visit https://micro-manager.github.io/ instead of https://micro-manager.github.io/micro-manager.org/ (the latter of which works now, but doesn't really work due to absolute paths coded into the site which don't point to the correct directory levels when using that URL base). Alternately, you could fix the absolute links to use relative ones (Jekyll has [the `relative_url` filter](https://jekyllrb.com/docs/liquid/filters/)).

**Comment by marktsuchida** [comment]
I'm going to do this rename tonight, some time after 8pm CDT -- it's just simpler for now, and we can always rename it back in the future if we need/want to.

**Comment by marktsuchida** [comment]
Done. Also, `gh-pages` has been renamed to `main` and is now the default branch.
