### ISSUE TITLE
Front page should have one-line description below logo

### ISSUE THREAD

**Issue by marktsuchida** [micro-manager/micro-manager.github.io#45]
And above the Get Started button.

"Optical microscope control and image acquisition"?

**Comment by nicost** [comment]
What about something along the lines of:

"Software interfacing your computer with microscope hardware"  ?

**Comment by marktsuchida** [comment]
Hmm. Because it says "Open source microscopy software" just above, I don't think we need to emphasize software and computer (and microscope, but that's hard to leave out). But "hardware" makes it very clear what MM is.

"Interface with microscope and image acquisition hardware"?
"Interactive control and automation of microscope hardware"?

**Comment by nicost** [comment]
Remove the "Open Source Microscopy Software" and replace with 

"Open Source Software for control and automation of microscope hardware"?

**Comment by marktsuchida** [comment]
It would be nice to not have to modify the logo.
How about just "Control and automation of microscope hardware"?

**Comment by nicost** [comment]
Perfect!
