### ISSUE TITLE
No clickable link to web host of documentation

### ISSUE THREAD

**Issue by Minimal-C** [micro-manager/micro-manager.github.io#80]
This is a fairly minor nitpick.
In the project "About" section there it mentions that this is "Micro-manager.org website".
There should be a clickable link.

Github has a website field in the "About" section edit menu which would be ideal to link to the actual web host for this documentation.

See here for an example of the https://github.com/opensourcedesign/opensourcedesign.github.io site:

![image](https://user-images.githubusercontent.com/11672160/146596206-69f7baaf-ef22-45b0-8fb9-c37bcc5f8aec.png)

**Comment by marktsuchida** [comment]
Fixed. Thanks.
