### ISSUE TITLE
Embedded youtube videos broken

### ISSUE THREAD

**Issue by henrypinkard** [micro-manager/micro-manager.github.io#86]
I noticed this on the Magellan page https://micro-manager.org/MicroMagellan

Easy enough to fix with a [thumbnail](https://www.darenmay.com/custommayd/developer/training/videos/markdown/2020/06/23/embed-youtube-video-in-markdown.html), anyone know if they can be embedded instead? Is there some way to do it with HTML?

**Comment by marktsuchida** [comment]
https://micro-manager.org/editing/videos, based on https://imagej.net/editing/videos.
