### ISSUE TITLE
Update python documentation

### ISSUE THREAD

**Issue by ianhi** [micro-manager/micro-manager.github.io#90]
## problem
https://micro-manager.org/Using_the_Micro-Manager_python_library Is mostly out of date.

It mentions pycro-manager which is good. But it doesn't mention pymmcore (or pymmcore-plus) however it does mention MMCorePy. Which I think is deprecated?

Then example code is fairly out of date in the sense of using python 2, otherwise I think with a switch to pymmcore it would most just work.

## solution

1. remove mentiosn of MMCorePy except one acknowledge it and saying it's deprecated
2. Add a mention of pymmcore
3. Add a mention of pymmcore-plus
4. Add link to the CMMCore api page

**Comment by marktsuchida** [comment]
Remaining to do: https://github.com/micro-manager/micro-manager.github.io/pull/95#issuecomment-1053709454
